# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'


networks:
  kornChain:
  tradent:

services:

  ca-@ORG:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-@ORG
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.@ORG.tradent.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.@ORG.tradent.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./@ORG-artifacts/crypto-config/peerOrganizations/@ORG.tradent.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-@ORG
    networks:
      - tradent


  peer0.@ORG.tradent.com:
    container_name: peer0.@ORG.tradent.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.@ORG.tradent.com
      - CORE_PEER_ADDRESS=peer0.@ORG.tradent.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.@ORG.tradent.com:7051
      - CORE_PEER_LOCALMSPID=@ORGMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./@ORG-artifacts/crypto-config/peerOrganizations/@ORG.tradent.com/peers/peer0.@ORG.tradent.com/msp:/etc/hyperledger/fabric/msp
        - ./@ORG-artifacts/crypto-config/peerOrganizations/@ORG.tradent.com/peers/peer0.@ORG.tradent.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - tradent


  @ORGcli:
    container_name: @ORGcli
    image: hyperledger/fabric-tools:${TAG}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=@ORGcli
      - CORE_PEER_ADDRESS=peer0.@ORG.tradent.com:7051
      - CORE_PEER_LOCALMSPID=@ORGMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/@ORG.tradent.com/peers/peer0.@ORG.tradent.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/@ORG.tradent.com/peers/peer0.@ORG.tradent.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/@ORG.tradent.com/peers/peer0.@ORG.tradent.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/@ORG.tradent.com/users/Admin@@ORG.tradent.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 10000'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./@ORG-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.@ORG.tradent.com
    networks:
      - tradent
